[package]
name = "qapro-rs"
version = "0.1.0"
authors = ["yutiansut <yutiansut@qq.com>"]
edition = "2018"
resolver = "2"

[dependencies]
serde_json = "*"
serde_derive = "1.0"
serde = { version = "1.0", features = ["derive"] } # 序列化

stopwatch = "*"


uuid = { version = "0.8", features = ["serde", "v1", "v4"] }
log = "0.4"
regex = "1"
log4rs = "0.13"

rayon ="1.5"
lazy_static = "1.4.0"

reqwest = "0.9.22"
csv = "1.1.3"
clap = "2.33"
toml = "0.5"
redis = "0.18.0"
amiquip = "0.4.0"


bson = "0.13.0"
mongodb = {version = "1.1.1", default-features = false, features = ["sync"]}

redis-async = { version = "0.8", default-features = false, features = ["tokio10"] }
actix-web-actors={ version = "4.0.0-beta.8", default-features = false }
actix-redis = "0.10.0-beta.4"
actix = "0.12.0"
actix-rt = "2.5.0"
actix-web ={ version = "4.0.0-beta.5" ,default-features = false }
actix-cors = "0.6.0-beta.7"

futures="0.3.5"
futures-executor = "^0.3"
futures-test = "^0.3"
futures-util = "^0.3"
async-trait= "*"
chrono-tz= { version = "0.5.3", features = ["serde"] }

chrono = "0.4.19"
thiserror = "1.0"
rand = "0.7"

arrow = {version='6.4.0',default-features = true,   features = ["csv", "prettyprint", "ipc"] }

datafusion = {version='6.0.0'}
[dependencies.polars]
git = "https://github.com/yutiansut/polars"
features = [
    "dynamic_groupby",
    "zip_with",
    "simd",
    "strings",

    "random",
    "object",
    "csv-file",
    "pretty_fmt",
    "performant",
    "dtype-full",
    "rows",
    "round_series",
    "is_first",
    "asof_join",
    "cross_join",
    "dot_product",
    "concat_str",
    "row_hash",
    "reinterpret",

    "mode",
    "extract_jsonpath",
    "lazy_regex",
    "cum_agg",
    "rolling_window",
    "interpolate",
    "list",
    "rank",
    "diff",
    "moment",
    "arange",
    "true_div",
    "dtype-categorical",
    "diagonal_concat",
    "horizontal_concat",
    "abs",
    "ewma"
]
[dependencies.clickhouse-rs]
git = "https://github.com/suharev7/clickhouse-rs"
branch = "async-await"
default-features = false
features = ["async_std"]